### ISSUE TITLE
Install via lazy.nvim

### ISSUE THREAD

**Issue by rogeriofrsouza** [martinsione/darkplus.nvim#4]
Is there a way to install this plugin via lazy.nvim?

**Comment by baco** [comment]
The plugin is not getting updates since 2021.  I think it may be unmaintained.  In my case I switched to [vscode.nvim](https://github.com/Mofiqul/vscode.nvim#vscodenvim)

**Comment by danyalutsevich** [comment]
whats the problem

`return {
	"martinsione/darkplus.nvim",
}`

<img width="801" alt="Screenshot 2024-07-15 at 20 42 17" src="https://github.com/user-attachments/assets/b12984f4-6ebf-4db6-9284-e2570d63931e">
